version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9.6

    working_directory: ~/podman-bot

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip3 install pipenv
            pipenv install
            pipenv run python3 index.py
      - run:
          name: flake8
          command: |
            pipenv run python3 -m flake8 --statistics