version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9.6

    working_directory: ~/podman-bot

    steps:
      - checkout
      - run:
          name: flake8
          command: |
            pip3 install flake8
            python3 -m flake8 --statistics